//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CantinaAgil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntradaSaida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EntradaSaida()
        {
            this.Transacao = new HashSet<Transacao>();
        }
    
        public int idEntradaSaida { get; set; }
        public System.DateTime dataEntradaSaida { get; set; }
        public int quantEntradaSaida { get; set; }
        public int idEstoque_EntradaSaida { get; set; }
        public Nullable<bool> ativoEntradaSaida { get; set; }
    
        public virtual Estoque Estoque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transacao> Transacao { get; set; }
    }
}
