//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CantinaAgil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estoque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estoque()
        {
            this.EntradaSaida = new HashSet<EntradaSaida>();
        }
    
        public int idEstoque { get; set; }
        public int quantidade { get; set; }
        public int idProduto_Estoque { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntradaSaida> EntradaSaida { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
