//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Cantina_agilEntities : DbContext
    {
        public Cantina_agilEntities()
            : base("name=Cantina_agilEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Atendente> Atendente { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<EntradaSaida> EntradaSaida { get; set; }
        public virtual DbSet<Estoque> Estoque { get; set; }
        public virtual DbSet<Produto> Produto { get; set; }
        public virtual DbSet<Sangria> Sangria { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Transacao> Transacao { get; set; }
    }
}
