//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacao
    {
        public int idTransacao { get; set; }
        public decimal valorTransacao { get; set; }
        public System.DateTime dataTransacao { get; set; }
        public bool pago { get; set; }
        public Nullable<System.DateTime> dataPagamento { get; set; }
        public int idEntradaSaida_Transacao { get; set; }
        public Nullable<int> idCliente_Transacao { get; set; }
        public Nullable<bool> ativoTransacao { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual EntradaSaida EntradaSaida { get; set; }
    }
}
