//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cantina_agil.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.SqlClient;

    public partial class Atendente
    {
        public Atendente(SqlDataReader leitor)
        {
            idAtendente = Convert.ToInt32(leitor["idAtendente"]);
            nomeAtendente = leitor["nomeAtendente"].ToString();
            loginAtendente = leitor["loginAtendente"].ToString();
            senhaAtendente = leitor["senhaAtendente"].ToString();
            emailAtendente = leitor["emailAtendente"].ToString();

            if (Convert.ToInt32(leitor["ativoAtendente"]) == 0)
            {
                ativoAtendente = false;
            }
            else
            {
                ativoAtendente = true;
            }

            cpf = leitor["cpf"].ToString();
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Atendente()
        {
            this.Sangria = new HashSet<Sangria>();
        }
    
        public int idAtendente { get; set; }
        public string nomeAtendente { get; set; }
        public string loginAtendente { get; set; }
        public string senhaAtendente { get; set; }
        public string emailAtendente { get; set; }
        public Nullable<bool> ativoAtendente { get; set; }
        public string cpf { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sangria> Sangria { get; set; }

    }
}
