//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cantina_agil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Transacao = new HashSet<Transacao>();
        }
    
        public int idCliente { get; set; }
        public string nomeCliente { get; set; }
        public string relacaoSenai { get; set; }
        public string emailCliente { get; set; }
        public string foneCliente { get; set; }
        public string celularCliente { get; set; }
        public string rgCliente { get; set; }
        public string cpfCliente { get; set; }
        public string obsCliente { get; set; }
        public Nullable<bool> ativoCliente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transacao> Transacao { get; set; }
    }
}
